<?php

namespace App\Enums;

enum SseEventEnum: string
{
    case INBOUND_ARRIVAL_SIGNAL = 'INBOUND_ARRIVAL_SIGNAL';
    case CAPACITY_LOAD_ALERT    = 'CAPACITY_LOAD_ALERT';
    case PACKAGE_PRIORITY_UPDATED = 'PACKAGE_PRIORITY_UPDATED';
    case SLA_BREACH_WARNING     = 'SLA_BREACH_WARNING';
}
